import { build } from "esbuild";
import { existsSync, readFileSync } from "node:fs";
import { relative, resolve } from "node:path";

const root = process.cwd();
const entryFile = resolve(root, "js/spicetifyWrapper/index.js");
const outputFile = resolve(root, "jsHelper/spicetifyWrapper.js");
const outputMapFile = `${outputFile}.map`;
const checkOnly = process.argv.includes("--check");

function normalizePath(filePath) {
  return relative(root, filePath).replaceAll("\\", "/");
}

async function buildWrapper(write) {
  const result = await build({
    banner: {
      js: "/* Generated by scripts/build-wrapper.mjs. Do not edit directly. */",
    },
    bundle: true,
    entryPoints: [entryFile],
    format: "iife",
    legalComments: "none",
    logLevel: "silent",
    minify: true,
    outfile: outputFile,
    sourcemap: true,
    sourcesContent: true,
    target: "chrome108",
    write,
  });

  return Object.fromEntries((result.outputFiles ?? []).map((file) => [file.path, file.text]));
}

if (checkOnly) {
  const generatedFiles = await buildWrapper(false);
  const filesToCheck = [outputFile, outputMapFile];

  for (const filePath of filesToCheck) {
    if (!existsSync(filePath)) continue;

    const current = readFileSync(filePath, "utf8");
    if (current !== generatedFiles[filePath]) {
      console.error(`${normalizePath(filePath)} is out of date. Run pnpm build:wrapper.`);
      process.exit(1);
    }
  }
  process.exit(0);
}

await buildWrapper(true);
